version: '3.7'

services:
  spark-hadoop:
    image: spark
    build:
      context: .
    ports:
      - "2223:22"
    networks:
      - hadoop
    volumes:
      - hadoop_data:/data/hadoop  # Monta o volume hadoop_data
    secrets:
      - maps_key
      - weather_key
      - temp_dir
      - postgres_jar_path
      - database_dir
      - postgres_user
      - postgres_password

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba_password
      POSTGRES_DB: dashboards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hadoop

  hadoop-storage:
    image: ubuntu:20.04
    networks:
      - hadoop
    volumes:
      - hadoop_data:/data/hadoop
    command: tail -f /dev/null  # Mantém o container rodando

networks:
  hadoop:
    driver: bridge

volumes:
  postgres_data:
  hadoop_data:

secrets:
  maps_key:
    file: ./maps_key.txt
  weather_key:
    file: ./weather_key.txt
  temp_dir:
    file: ./temp_dir.txt
  postgres_jar_path:
    file: ./postgres_jar_path.txt
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt
  database_dir:
    file: ./database_dir.txt
